export const DEPARTMENT_DATA_START = "DEPARTMENT_DATA_START";
export const DEPARTMENT_DATA_SUCCESS = "DEPARTMENT_DATA_SUCCESS";
export const DEPARTMENT_DATA_FAILURE = "DEPARTMENT_DATA_FAILURE";

export const STORE_DATA_START = "STORE_DATA_START";
export const STORE_DATA_SUCCESS = "STORE_DATA_SUCCESS";
export const STORE_DATA_FAILURE = "STORE_DATA_FAILURE";

export const GROUP_DATA_START = "GROUP_DATA_START";
export const GROUP_DATA_SUCCESS = "GROUP_DATA_SUCCESS";
export const GROUP_DATA_FAILURE = "GROUP_DATA_FAILURE";

export const SEARCH_DATA_START = "SEARCH_DATA_START";
export const SEARCH_DATA_SUCCESS = "SEARCH_DATA_SUCCESS";
export const SEARCH_DATA_FAILURE = "SEARCH_DATA_SUCCESS";

export const CREATE_COUPON_START = "CREATE_COUPON_START";
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";
export const  CREATE_COUPON_FAILURE= "CREATE_COUPON_FAILURE";

export const CREATE_UPC_START ="CREATE_UPC_START";
export const CREATE_UPC_SUCCESS ="CREATE_UPC_SUCCESS";
export const CREATE_UPC_FAILURE ="CREATE_UPC_FAILURE";

export const GET_PRODUCT_START ="GET_PRODUCT_START";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE";

export const GET_MEMBER_START ="GET_MEMBER_START";
export const GET_MEMBER_SUCCESS="GET_MEMBER_SUCCESS";
export const GET_MEMBER_FAILURE="GET_MEMBER_FAILURE";


export const DEPT_STORE_DATA_START = "DEPT_STORE_DATA_START";
export const DEPT_STORE_DATA_SUCCESS = "DEPT_STORE_DATA_SUCCESS";
export const DEPT_STORE_DATA_FAILURE = "DEPT_STORE_DATA_FAILURE";

export const GET_DEPT_STORE_START = "GET_DEPT_STORE_START";
export const GET_DEPT_STORE_SUCCESS="GET_DEPT_STORE_SUCCESS";
export const GET_DEPT_STORE_FAILURE = "GET_DEPT_STORE_FAILURE";